"""Deterministic, simulation-only sensor-placement recommendation tools.

The package consumes a declared placement request and a geometry/physics
survey exported by Unreal.  Its outputs remain review artifacts: importing
this package never edits an Unreal project or publishes sites to C2.
"""

from .aoi import generate_circular_samples, horizontal_distance_meters
from .contracts import (
    FAMILY_NAMES,
    RECOMMENDATION_SCHEMA,
    REQUEST_SCHEMA,
    SURVEY_SCHEMA,
    UNREAL_PATCH_SCHEMA,
    AreaOfInterest,
    CandidateOption,
    CoverageEvaluation,
    CoverageSample,
    GeoPoint,
    PlacementConstraints,
    PlacementRecommendation,
    PlacementRequest,
    PlacementScenario,
    PlacementSurvey,
    SamplingPlan,
    SensorPackage,
    canonical_json,
    family_for_modality,
    stable_digest,
)
from .coverage import (
    active_families,
    angular_difference_degrees,
    build_coverage_evaluation,
    build_eligible_evaluation_index,
    evaluate_selection,
    within_horizontal_fov,
)
from .optimizer import (
    EXACT_ALGORITHM,
    GREEDY_ALGORITHM,
    option_installed_cost,
    selection_cost,
    solve_placement,
)
from .evidence_intake import (
    CANDIDATE_CATALOG_SCHEMA,
    EVIDENCE_INTAKE_MANIFEST_SCHEMA,
    EVIDENCE_INTAKE_RECEIPT_SCHEMA,
    EVALUATOR_EVIDENCE_SCHEMA,
    EVALUATOR_RESULT_ROW_FIELDS,
    ROBUST_OUTCOME_SEMANTICS_NOT_VALIDATED,
    SCENARIO_PARTITION_SCHEMA,
    TRAJECTORY_CORPUS_SCHEMA,
    evaluator_result_rows_sha256,
    validate_evidence_intake,
)
from .planning_pipeline import (
    BRANCH_AND_BOUND_ALGORITHM,
    CANDIDATE_TRAJECTORY_PRECOMPUTE_SCHEMA,
    GREEDY_LOCAL_ALGORITHM,
    CandidateSensorPose,
    PoseBounds,
    RobustDemand,
    RobustStaticProblem,
    SensorModelCalibration,
    StaticCandidate,
    TargetTrajectory,
    TrajectoryPoint,
    assess_stage0_readiness,
    build_calibration_bundle,
    compare_pose_refiners,
    default_synthetic_demo_calibrations,
    load_and_validate_rf_geometry,
    precompute_demo_candidate_trajectory_results,
    solve_greedy_local_search,
    solve_robust_branch_and_bound,
    static_problem_from_precompute,
    validate_precompute_truth_contract,
)
from .report import render_markdown
from .study_contract import (
    ALLOWED_SENSOR_CLASSES,
    PROHIBITED_DEPLOYED_MODALITIES,
    STAGE0_STUDY_SCHEMA,
    STAGE0_VALIDATION_RECEIPT_SCHEMA,
    Stage0StudyContract,
    validate_stage0_study_contract,
)
from .unreal_config import build_unreal_sensor_nodes_patch

__all__ = [
    "EXACT_ALGORITHM",
    "EVIDENCE_INTAKE_MANIFEST_SCHEMA",
    "EVIDENCE_INTAKE_RECEIPT_SCHEMA",
    "EVALUATOR_EVIDENCE_SCHEMA",
    "EVALUATOR_RESULT_ROW_FIELDS",
    "FAMILY_NAMES",
    "GREEDY_ALGORITHM",
    "GREEDY_LOCAL_ALGORITHM",
    "BRANCH_AND_BOUND_ALGORITHM",
    "ALLOWED_SENSOR_CLASSES",
    "PROHIBITED_DEPLOYED_MODALITIES",
    "RECOMMENDATION_SCHEMA",
    "ROBUST_OUTCOME_SEMANTICS_NOT_VALIDATED",
    "REQUEST_SCHEMA",
    "STAGE0_STUDY_SCHEMA",
    "STAGE0_VALIDATION_RECEIPT_SCHEMA",
    "SURVEY_SCHEMA",
    "UNREAL_PATCH_SCHEMA",
    "AreaOfInterest",
    "CandidateSensorPose",
    "CandidateOption",
    "CANDIDATE_CATALOG_SCHEMA",
    "CoverageEvaluation",
    "CoverageSample",
    "GeoPoint",
    "PoseBounds",
    "PlacementConstraints",
    "PlacementRecommendation",
    "PlacementRequest",
    "PlacementScenario",
    "PlacementSurvey",
    "SamplingPlan",
    "SCENARIO_PARTITION_SCHEMA",
    "SensorPackage",
    "SensorModelCalibration",
    "StaticCandidate",
    "RobustDemand",
    "RobustStaticProblem",
    "TargetTrajectory",
    "TrajectoryPoint",
    "TRAJECTORY_CORPUS_SCHEMA",
    "Stage0StudyContract",
    "active_families",
    "assess_stage0_readiness",
    "angular_difference_degrees",
    "build_coverage_evaluation",
    "build_eligible_evaluation_index",
    "build_unreal_sensor_nodes_patch",
    "build_calibration_bundle",
    "canonical_json",
    "compare_pose_refiners",
    "default_synthetic_demo_calibrations",
    "evaluate_selection",
    "evaluator_result_rows_sha256",
    "family_for_modality",
    "generate_circular_samples",
    "horizontal_distance_meters",
    "load_and_validate_rf_geometry",
    "option_installed_cost",
    "render_markdown",
    "precompute_demo_candidate_trajectory_results",
    "selection_cost",
    "solve_placement",
    "solve_greedy_local_search",
    "solve_robust_branch_and_bound",
    "stable_digest",
    "static_problem_from_precompute",
    "validate_stage0_study_contract",
    "validate_evidence_intake",
    "validate_precompute_truth_contract",
    "within_horizontal_fov",
    "CANDIDATE_TRAJECTORY_PRECOMPUTE_SCHEMA",
]
