"""Simulation-only RF and sensor-fusion primitives.

The public API deliberately stops at observations and conservative evidence
fusion. It contains no response, engagement, or weapon-control behavior.
"""

from .config import (
    DroneRFEmitterConfig,
    RFChannelConfig,
    SensorNodeConfig,
    SimulationConfig,
    load_simulation_config,
)
from .fusion import (
    ConservativeFusionResult,
    ProbabilityEvidence,
    conservative_confidence_fusion,
)
from .fusion_v2 import (
    FUSION_V2_METHOD,
    FUSION_V2_SCHEMA_VERSION,
    SCENARIO_ASSUMPTION_NOTICE,
    SCORE_SEMANTICS,
    WEATHER_PROFILES,
    FusionEvidenceV2,
    FusionModality,
    FusionPolicyV2,
    FusionResultV2,
    ModalityContributionV2,
    WeatherProfile,
    fuse_track_evidence_v2,
    reference_scenario_evidence,
    run_reference_weather_sweep,
)
from .fusion_v3 import (
    FUSION_V3_METHOD,
    LayeredEvidence,
    LayeredFusionPolicy,
    LayeredModality,
    fuse_layered_evidence,
)
from .geodesy import (
    ECEF,
    ENU,
    Geodetic,
    ecef_to_enu,
    ecef_to_geodetic,
    enu_to_ecef,
    enu_to_geodetic,
    geodetic_to_ecef,
    geodetic_to_enu,
)
from .observations import SensorModality, SensorObservation
from .mmwave import (
    MMWAVE_METHOD,
    MmWaveDetection,
    MmWaveRadar,
    simulate_mmwave_detection,
)
from .rf import (
    AnalyticDetectionEstimate,
    DeterministicShadowing,
    LinkContext,
    analytic_energy_detector_probability,
    dbm_to_mw,
    fixed_los_nlos_loss_hook,
    fspl_db,
    log_distance_path_loss_db,
    mw_to_dbm,
    received_power_dbm,
    sum_powers_dbm,
    thermal_noise_dbm,
)
from .synthetic import (
    BAND_2_4_GHZ,
    BAND_5_8_GHZ,
    IQFrame,
    PSDFrame,
    generate_synthetic_iq,
    welch_psd,
)
from .wideband_rf import (
    WIDEBAND_RF_METHOD,
    RFEmitterProfile,
    WidebandChannel,
    WidebandReceiver,
    WidebandRFDetection,
    simulate_wideband_link,
)

__all__ = [
    "AnalyticDetectionEstimate",
    "BAND_2_4_GHZ",
    "BAND_5_8_GHZ",
    "ConservativeFusionResult",
    "DeterministicShadowing",
    "DroneRFEmitterConfig",
    "ECEF",
    "ENU",
    "FUSION_V2_METHOD",
    "FUSION_V2_SCHEMA_VERSION",
    "FUSION_V3_METHOD",
    "FusionEvidenceV2",
    "FusionModality",
    "FusionPolicyV2",
    "FusionResultV2",
    "Geodetic",
    "IQFrame",
    "LayeredEvidence",
    "LayeredFusionPolicy",
    "LayeredModality",
    "LinkContext",
    "ModalityContributionV2",
    "MMWAVE_METHOD",
    "MmWaveDetection",
    "MmWaveRadar",
    "PSDFrame",
    "ProbabilityEvidence",
    "RFChannelConfig",
    "RFEmitterProfile",
    "SensorModality",
    "SensorNodeConfig",
    "SensorObservation",
    "SimulationConfig",
    "SCENARIO_ASSUMPTION_NOTICE",
    "SCORE_SEMANTICS",
    "WEATHER_PROFILES",
    "WeatherProfile",
    "WIDEBAND_RF_METHOD",
    "WidebandChannel",
    "WidebandReceiver",
    "WidebandRFDetection",
    "analytic_energy_detector_probability",
    "conservative_confidence_fusion",
    "dbm_to_mw",
    "ecef_to_enu",
    "ecef_to_geodetic",
    "enu_to_ecef",
    "enu_to_geodetic",
    "fspl_db",
    "fixed_los_nlos_loss_hook",
    "generate_synthetic_iq",
    "fuse_track_evidence_v2",
    "fuse_layered_evidence",
    "geodetic_to_ecef",
    "geodetic_to_enu",
    "load_simulation_config",
    "log_distance_path_loss_db",
    "mw_to_dbm",
    "received_power_dbm",
    "reference_scenario_evidence",
    "run_reference_weather_sweep",
    "simulate_mmwave_detection",
    "simulate_wideband_link",
    "sum_powers_dbm",
    "thermal_noise_dbm",
    "welch_psd",
]
