"""Bounded validation of Unreal Singapore sensor-fusion campaign artifacts.

This module validates simulation telemetry and capture integrity.  It does not
claim physical RF calibration, real-world performance, or engagement ability.
All input reads are bounded and all reported model/ground-truth comparisons are
explicitly scoped to scenario truth generated by the simulator.
"""

from __future__ import annotations

import argparse
from collections import defaultdict
from dataclasses import dataclass, field
from datetime import datetime, timezone
import hashlib
import json
import math
import os
from pathlib import Path
import statistics
import tempfile
from typing import Any, Iterable, Mapping, Sequence

from .paths import DEFAULT_TRIAD_CONFIG, DEFAULT_TRIAD_SENSOR_SAVED_DIR

SPEED_OF_LIGHT_M_S = 299_792_458.0
BOLTZMANN_J_K = 1.380_649e-23
REFERENCE_TEMPERATURE_K = 290.0
DEFAULT_SAVED_DIR = DEFAULT_TRIAD_SENSOR_SAVED_DIR
DEFAULT_CONFIG_PATH = DEFAULT_TRIAD_CONFIG
DEFAULT_MAX_RF_RECORDS = 250_000
DEFAULT_MAX_ALERT_RECORDS = 25_000
DEFAULT_MAX_FRAMES = 500
MAX_RF_RECORDS_HARD_LIMIT = 1_000_000
MAX_ALERT_RECORDS_HARD_LIMIT = 100_000
MAX_FRAMES_HARD_LIMIT = 2_000
MAX_JSONL_LINE_BYTES = 1_048_576
MAX_METADATA_BYTES = 262_144
MAX_EVENT_REPORT_BYTES = 32 * 1024 * 1024
MAX_HASH_FILE_BYTES = 128 * 1024 * 1024
FSPL_TOLERANCE_DB = 0.05
NOISE_TOLERANCE_DB = 0.10
SNR_TOLERANCE_DB = 0.01
DUAL_BAND_GAP_TOLERANCE_DB = 0.05


def _utc_now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="microseconds").replace(
        "+00:00", "Z"
    )


def _status_rank(status: str) -> int:
    return {"pass": 0, "warn": 1, "fail": 2}[status]


def _check(
    check_id: str,
    status: str,
    message: str,
    **metrics: object,
) -> dict[str, object]:
    if status not in {"pass", "warn", "fail"}:
        raise ValueError(f"invalid check status: {status}")
    result: dict[str, object] = {
        "id": check_id,
        "status": status,
        "message": message,
    }
    if metrics:
        result["metrics"] = metrics
    return result


def _finite_number(value: object) -> float | None:
    if isinstance(value, bool):
        return None
    try:
        result = float(value)  # type: ignore[arg-type]
    except (TypeError, ValueError, OverflowError):
        return None
    return result if math.isfinite(result) else None


def _truth_value(value: object) -> bool | None:
    if isinstance(value, bool):
        return value
    if isinstance(value, str):
        lowered = value.strip().lower()
        if lowered in {"true", "hostile", "enemy", "1", "yes"}:
            return True
        if lowered in {"false", "friendly", "neutral", "0", "no"}:
            return False
    if isinstance(value, (int, float)) and value in {0, 1}:
        return bool(value)
    return None


def _record_truth(record: Mapping[str, object]) -> bool | None:
    for key in (
        "hostileScenarioTruth",
        "isHostileScenarioTruth",
        "hostileTruth",
        "isHostile",
    ):
        if key in record:
            return _truth_value(record.get(key))
    return None


def _parse_timestamp(value: object) -> float | None:
    numeric = _finite_number(value)
    if numeric is not None:
        return numeric
    if not isinstance(value, str) or not value.strip():
        return None
    raw = value.strip()
    try:
        parsed = datetime.fromisoformat(raw.replace("Z", "+00:00"))
    except ValueError:
        return None
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=timezone.utc)
    return parsed.timestamp()


def _record_time(record: Mapping[str, object]) -> tuple[float | None, str]:
    for key in ("simulationSeconds", "simulationTimeSeconds", "sampleSeconds"):
        value = _finite_number(record.get(key))
        if value is not None:
            return value, "simulation"
    for key in ("timestampUtc", "timestamp", "generatedAtUtc"):
        value = _parse_timestamp(record.get(key))
        if value is not None:
            return value, "utc"
    return None, "missing"


def _positive_bounded(name: str, value: int, hard_limit: int) -> int:
    if isinstance(value, bool) or not isinstance(value, int):
        raise TypeError(f"{name} must be an integer")
    if value <= 0 or value > hard_limit:
        raise ValueError(f"{name} must be in [1, {hard_limit}]")
    return value


def _load_json_object(path: Path, maximum_bytes: int) -> dict[str, object]:
    size = path.stat().st_size
    if size > maximum_bytes:
        raise ValueError(f"{path.name} exceeds the {maximum_bytes}-byte safety limit")
    with path.open("rb") as handle:
        data = handle.read(maximum_bytes + 1)
    if len(data) > maximum_bytes:
        raise ValueError(f"{path.name} exceeds the {maximum_bytes}-byte safety limit")
    parsed = json.loads(data.decode("utf-8-sig"))
    if not isinstance(parsed, dict):
        raise ValueError(f"{path.name} must contain a JSON object")
    return parsed


def _read_jsonl_bounded(
    path: Path,
    *,
    max_records: int,
) -> tuple[list[dict[str, object]], dict[str, object], list[dict[str, object]]]:
    records: list[dict[str, object]] = []
    checks: list[dict[str, object]] = []
    invalid_lines = 0
    overlong_lines = 0
    lines_examined = 0
    truncated = False
    if not path.is_file():
        checks.append(_check("input.file_exists", "fail", f"Input does not exist: {path}"))
        return records, {
            "path": str(path),
            "lines_examined": 0,
            "records_read": 0,
            "invalid_lines": 0,
            "overlong_lines": 0,
            "truncated_by_record_limit": False,
        }, checks

    with path.open("rb") as handle:
        for raw in handle:
            lines_examined += 1
            if len(records) >= max_records:
                truncated = True
                break
            if len(raw) > MAX_JSONL_LINE_BYTES:
                overlong_lines += 1
                continue
            if not raw.strip():
                continue
            try:
                decoded = json.loads(raw.decode("utf-8-sig"))
            except (UnicodeDecodeError, json.JSONDecodeError):
                invalid_lines += 1
                continue
            if not isinstance(decoded, dict):
                invalid_lines += 1
                continue
            records.append(decoded)

    invalid_total = invalid_lines + overlong_lines
    status = "pass" if invalid_total == 0 else "fail"
    checks.append(
        _check(
            "input.jsonl_integrity",
            status,
            "Every examined non-empty JSONL line was a bounded JSON object."
            if status == "pass"
            else "One or more JSONL lines were invalid or exceeded the safety limit.",
            invalid_lines=invalid_lines,
            overlong_lines=overlong_lines,
            records_read=len(records),
        )
    )
    if truncated:
        checks.append(
            _check(
                "input.record_limit",
                "warn",
                "The campaign read was truncated at the configured record limit.",
                max_records=max_records,
            )
        )
    return records, {
        "path": str(path.resolve()),
        "lines_examined": lines_examined,
        "records_read": len(records),
        "invalid_lines": invalid_lines,
        "overlong_lines": overlong_lines,
        "truncated_by_record_limit": truncated,
    }, checks


def _newest_jsonl(directory: Path, prefix: str) -> Path | None:
    if not directory.is_dir():
        return None
    candidates = [
        path for path in directory.glob(f"{prefix}*.jsonl") if path.is_file()
    ]
    if not candidates:
        return None
    return max(candidates, key=lambda item: (item.stat().st_mtime_ns, item.name))


def _scenario_config(path: Path | None) -> tuple[dict[str, object], list[dict[str, object]]]:
    checks: list[dict[str, object]] = []
    if path is None or not path.is_file():
        checks.append(
            _check(
                "config.available",
                "warn",
                "Scenario config was unavailable; checks requiring receiver settings are skipped.",
                path=None if path is None else str(path),
            )
        )
        return {}, checks
    try:
        config = _load_json_object(path, 4 * 1024 * 1024)
    except (OSError, UnicodeDecodeError, json.JSONDecodeError, ValueError) as exc:
        checks.append(_check("config.readable", "fail", f"Could not read scenario config: {exc}"))
        return {}, checks
    checks.append(_check("config.readable", "pass", "Scenario config is readable.", path=str(path.resolve())))
    return config, checks


def _node_settings(config: Mapping[str, object]) -> dict[str, dict[str, object]]:
    result: dict[str, dict[str, object]] = {}
    nodes = config.get("SensorNodes", config.get("sensorNodes", []))
    if not isinstance(nodes, list):
        return result
    for raw in nodes:
        if not isinstance(raw, dict):
            continue
        node_id = raw.get("NodeId", raw.get("nodeId"))
        if isinstance(node_id, str) and node_id:
            result[node_id] = raw
    return result


def _config_value(
    record: Mapping[str, object],
    settings: Mapping[str, object],
    record_keys: Sequence[str],
    config_keys: Sequence[str],
) -> float | None:
    for key in record_keys:
        value = _finite_number(record.get(key))
        if value is not None:
            return value
    for key in config_keys:
        value = _finite_number(settings.get(key))
        if value is not None:
            return value
    return None


def _independent_fspl_db(distance_m: float, frequency_ghz: float) -> float:
    return 20.0 * math.log10(
        4.0 * math.pi * distance_m * frequency_ghz * 1.0e9 / SPEED_OF_LIGHT_M_S
    )


def _independent_noise_dbm(bandwidth_hz: float, noise_figure_db: float) -> float:
    watts = BOLTZMANN_J_K * REFERENCE_TEMPERATURE_K * bandwidth_hz
    return 10.0 * math.log10(watts / 1.0e-3) + noise_figure_db


@dataclass
class _Aggregate:
    records: int = 0
    detected: int = 0
    los: int = 0
    snr: list[float] = field(default_factory=list)
    ranges: list[float] = field(default_factory=list)

    def add(self, record: Mapping[str, object]) -> None:
        self.records += 1
        if record.get("detected") is True:
            self.detected += 1
        if record.get("lineOfSight") is True:
            self.los += 1
        snr = _finite_number(record.get("snrDb"))
        distance = _finite_number(record.get("distanceMeters"))
        if snr is not None:
            self.snr.append(snr)
        if distance is not None:
            self.ranges.append(distance)

    def to_dict(self, key_name: str, key: str) -> dict[str, object]:
        return {
            key_name: key,
            "records": self.records,
            "detections": self.detected,
            "detection_rate": self.detected / self.records if self.records else None,
            "line_of_sight_rate": self.los / self.records if self.records else None,
            "snr_db": _distribution(self.snr),
            "range_m": _distribution(self.ranges),
        }


def _distribution(values: Sequence[float]) -> dict[str, float | int | None]:
    if not values:
        return {"count": 0, "minimum": None, "mean": None, "maximum": None}
    return {
        "count": len(values),
        "minimum": min(values),
        "mean": math.fsum(values) / len(values),
        "maximum": max(values),
    }


def _sample_key(record: Mapping[str, object]) -> str | None:
    for key in ("sampleId", "sampleIndex", "sampleSequence"):
        if key in record:
            return str(record[key])
    value = _finite_number(record.get("simulationSeconds"))
    if value is not None:
        return f"sim:{value:.6f}"
    timestamp = record.get("timestampUtc", record.get("timestamp"))
    return f"utc:{timestamp}" if isinstance(timestamp, str) and timestamp else None


def _target_name(record: Mapping[str, object]) -> str:
    for key in ("targetActor", "targetActorName", "targetId", "trackId"):
        value = record.get(key)
        if isinstance(value, str) and value:
            return value
    return "<unknown-target>"


def _node_name(record: Mapping[str, object]) -> str:
    value = record.get("nodeId", record.get("sensorNodeId"))
    return value if isinstance(value, str) and value else "<unknown-node>"


def _validate_rf(
    records: Sequence[dict[str, object]],
    config: Mapping[str, object],
    *,
    confirming_nodes_min: int,
) -> tuple[dict[str, object], list[dict[str, object]], dict[tuple[str, str], dict[str, object]]]:
    checks: list[dict[str, object]] = []
    node_config = _node_settings(config)
    require_los = _truth_value(
        config.get(
            "bRequireLineOfSightForDetection",
            config.get("requireLineOfSightForDetection", False),
        )
    ) is True
    fspl_residuals: list[float] = []
    noise_residuals: list[float] = []
    snr_residuals: list[float] = []
    invalid_math_records = 0
    gate_compared = 0
    gate_mismatch = 0
    truth_known = 0
    aggregates: dict[str, dict[str, _Aggregate]] = {
        "by_band": defaultdict(_Aggregate),
        "by_node": defaultdict(_Aggregate),
        "by_hostile_truth": defaultdict(_Aggregate),
    }
    dual_band: dict[tuple[str, str, str], dict[float, float]] = defaultdict(dict)
    sample_targets: dict[tuple[str, str], dict[str, object]] = {}

    for record in records:
        node_id = _node_name(record)
        target = _target_name(record)
        frequency = _finite_number(record.get("frequencyGHz"))
        distance = _finite_number(record.get("distanceMeters"))
        reported_fspl = _finite_number(record.get("freeSpacePathLossDb"))
        noise = _finite_number(record.get("noiseFloorDbm"))
        received = _finite_number(record.get("receivedPowerDbm"))
        snr = _finite_number(record.get("snrDb"))
        truth = _record_truth(record)
        if truth is not None:
            truth_known += 1
        band_key = "unknown" if frequency is None else f"{frequency:g}GHz"
        truth_key = "unknown" if truth is None else ("hostile" if truth else "non_hostile")
        aggregates["by_band"][band_key].add(record)
        aggregates["by_node"][node_id].add(record)
        aggregates["by_hostile_truth"][truth_key].add(record)

        if (
            frequency is not None
            and frequency > 0.0
            and distance is not None
            and distance > 0.0
            and reported_fspl is not None
        ):
            fspl_residuals.append(reported_fspl - _independent_fspl_db(distance, frequency))
        else:
            invalid_math_records += 1

        settings = node_config.get(node_id, {})
        bandwidth_mhz = _config_value(
            record,
            settings,
            ("bandwidthMHz",),
            ("BandwidthMHz", "bandwidthMHz"),
        )
        bandwidth_hz = _config_value(
            record,
            settings,
            ("bandwidthHz",),
            ("BandwidthHz", "bandwidthHz"),
        )
        if bandwidth_hz is None and bandwidth_mhz is not None:
            bandwidth_hz = bandwidth_mhz * 1.0e6
        noise_figure = _config_value(
            record,
            settings,
            ("noiseFigureDb",),
            ("NoiseFigureDb", "noiseFigureDb"),
        )
        if noise is not None and bandwidth_hz is not None and bandwidth_hz > 0 and noise_figure is not None:
            noise_residuals.append(noise - _independent_noise_dbm(bandwidth_hz, noise_figure))
        if snr is not None and received is not None and noise is not None:
            snr_residuals.append(snr - (received - noise))

        booleans = [
            record.get("frequencySupported"),
            record.get("inRange"),
            record.get("aboveSensitivity"),
            record.get("detected"),
            record.get("lineOfSight"),
        ]
        if all(isinstance(value, bool) for value in booleans):
            gate_compared += 1
            expected = bool(record["frequencySupported"]) and bool(record["inRange"]) and bool(record["aboveSensitivity"])
            if require_los:
                expected = expected and bool(record["lineOfSight"])
            if expected is not bool(record["detected"]):
                gate_mismatch += 1

        sample = _sample_key(record)
        if sample is not None:
            entry = sample_targets.setdefault(
                (sample, target),
                {
                    "sample": sample,
                    "target": target,
                    "truth": truth,
                    "detected_nodes": set(),
                    "all_nodes": set(),
                    "simulation_seconds": _finite_number(record.get("simulationSeconds")),
                },
            )
            entry["all_nodes"].add(node_id)  # type: ignore[union-attr]
            if record.get("detected") is True:
                entry["detected_nodes"].add(node_id)  # type: ignore[union-attr]
            if entry["truth"] is None and truth is not None:
                entry["truth"] = truth
            if frequency in {2.4, 5.8} and reported_fspl is not None:
                dual_band[(sample, node_id, target)][frequency] = reported_fspl

    if not records:
        checks.append(_check("rf.records_present", "fail", "No RF telemetry records were available."))
    else:
        checks.append(_check("rf.records_present", "pass", "RF telemetry records were available.", records=len(records)))

    def residual_check(
        check_id: str,
        residuals: Sequence[float],
        tolerance: float,
        description: str,
    ) -> None:
        if not residuals:
            checks.append(_check(check_id, "warn", f"{description} could not be recomputed from available fields."))
            return
        maximum = max(abs(value) for value in residuals)
        status = "pass" if maximum <= tolerance else "fail"
        checks.append(
            _check(
                check_id,
                status,
                f"{description} residuals are within tolerance."
                if status == "pass"
                else f"{description} residuals exceed tolerance.",
                compared=len(residuals),
                max_absolute_residual_db=maximum,
                mean_residual_db=math.fsum(residuals) / len(residuals),
                tolerance_db=tolerance,
            )
        )

    residual_check("rf.fspl_recomputation", fspl_residuals, FSPL_TOLERANCE_DB, "Independent FSPL")
    residual_check("rf.ktb_noise_recomputation", noise_residuals, NOISE_TOLERANCE_DB, "Independent kTB plus noise-figure")
    residual_check("rf.snr_arithmetic", snr_residuals, SNR_TOLERANCE_DB, "SNR arithmetic")
    if gate_compared == 0:
        checks.append(_check("rf.detection_gate_consistency", "warn", "Boolean detection-gate fields were unavailable."))
    else:
        checks.append(
            _check(
                "rf.detection_gate_consistency",
                "pass" if gate_mismatch == 0 else "fail",
                "All boolean detection gates are internally consistent."
                if gate_mismatch == 0
                else "One or more detection results disagree with their boolean gates.",
                compared=gate_compared,
                mismatches=gate_mismatch,
                line_of_sight_required=require_los,
            )
        )

    expected_gap = 20.0 * math.log10(5.8 / 2.4)
    gap_residuals: list[float] = []
    for values in dual_band.values():
        if 2.4 in values and 5.8 in values:
            gap_residuals.append((values[5.8] - values[2.4]) - expected_gap)
    if not gap_residuals:
        checks.append(_check("rf.dual_band_fspl_gap", "warn", "No same-link 2.4/5.8 GHz pairs were available."))
    else:
        maximum_gap_residual = max(abs(value) for value in gap_residuals)
        checks.append(
            _check(
                "rf.dual_band_fspl_gap",
                "pass" if maximum_gap_residual <= DUAL_BAND_GAP_TOLERANCE_DB else "fail",
                "The same-link 5.8-vs-2.4 GHz loss gap matches the frequency-ratio expectation."
                if maximum_gap_residual <= DUAL_BAND_GAP_TOLERANCE_DB
                else "The same-link dual-band loss gap is inconsistent.",
                pairs=len(gap_residuals),
                expected_gap_db=expected_gap,
                mean_observed_gap_db=expected_gap + math.fsum(gap_residuals) / len(gap_residuals),
                max_absolute_residual_db=maximum_gap_residual,
            )
        )

    if truth_known == 0:
        checks.append(
            _check(
                "rf.scenario_truth_available",
                "warn",
                "hostileScenarioTruth is absent; older telemetry is supported but hostile/friendly scoring is unavailable.",
            )
        )
    else:
        status = "pass" if truth_known == len(records) else "warn"
        checks.append(
            _check(
                "rf.scenario_truth_available",
                status,
                "Scenario hostile truth is present on every RF record."
                if status == "pass"
                else "Scenario hostile truth is present on only some RF records.",
                known_records=truth_known,
                total_records=len(records),
            )
        )

    coverage_rows: list[dict[str, object]] = []
    eligible_hostile = 0
    multi_node_hostile = 0
    swarm_samples = 0
    multi_node_swarm = 0
    for entry in sample_targets.values():
        nodes = sorted(entry["detected_nodes"])  # type: ignore[arg-type]
        truth = entry["truth"]
        is_swarm = "swarm" in str(entry["target"]).lower()
        covered = len(nodes) >= confirming_nodes_min
        if truth is True:
            eligible_hostile += 1
            multi_node_hostile += int(covered)
        if is_swarm:
            swarm_samples += 1
            multi_node_swarm += int(covered)
        coverage_rows.append(
            {
                "sample": entry["sample"],
                "target": entry["target"],
                "hostile_scenario_truth": truth,
                "is_swarm_named_target": is_swarm,
                "detected_node_count": len(nodes),
                "detected_nodes": nodes,
                "meets_multi_node_threshold": covered,
                "simulation_seconds": entry["simulation_seconds"],
            }
        )
    coverage_rows.sort(key=lambda row: (str(row["sample"]), str(row["target"])))
    if not coverage_rows:
        checks.append(_check("rf.multi_node_coverage", "warn", "No sample identity was available for multi-node coverage."))
    elif eligible_hostile == 0 and swarm_samples == 0:
        checks.append(_check("rf.multi_node_coverage", "warn", "No hostile-truth or swarm-named sample could be scored for multi-node coverage."))
    else:
        checks.append(
            _check(
                "rf.multi_node_coverage",
                "pass" if (multi_node_hostile > 0 or multi_node_swarm > 0) else "fail",
                "At least one hostile/swarm target sample had multi-node coverage."
                if (multi_node_hostile > 0 or multi_node_swarm > 0)
                else "No hostile/swarm target sample reached the multi-node threshold.",
                confirming_nodes_min=confirming_nodes_min,
                hostile_target_samples=eligible_hostile,
                hostile_multi_node_samples=multi_node_hostile,
                swarm_named_target_samples=swarm_samples,
                swarm_multi_node_samples=multi_node_swarm,
            )
        )

    group_output: dict[str, list[dict[str, object]]] = {}
    key_names = {"by_band": "band", "by_node": "node_id", "by_hostile_truth": "hostile_truth"}
    for grouping, groups in aggregates.items():
        group_output[grouping] = [
            groups[key].to_dict(key_names[grouping], key) for key in sorted(groups)
        ]

    summary = {
        "record_count": len(records),
        "invalid_or_incomplete_math_record_count": invalid_math_records,
        "aggregates": group_output,
        "residuals_db": {
            "fspl": _distribution(fspl_residuals),
            "ktb_plus_noise_figure": _distribution(noise_residuals),
            "snr_arithmetic": _distribution(snr_residuals),
        },
        "dual_band": {
            "same_link_pairs": len(gap_residuals),
            "expected_5_8_minus_2_4_db": expected_gap,
            "gap_residual_db": _distribution(gap_residuals),
        },
        "multi_node_coverage": {
            "confirming_nodes_min": confirming_nodes_min,
            "target_sample_count": len(coverage_rows),
            "hostile_target_samples": eligible_hostile,
            "hostile_multi_node_samples": multi_node_hostile,
            "swarm_named_target_samples": swarm_samples,
            "swarm_multi_node_samples": multi_node_swarm,
            "samples": coverage_rows[:2_000],
            "samples_truncated": len(coverage_rows) > 2_000,
        },
        "scope": "simulation telemetry consistency; not physical RF calibration",
    }
    return summary, checks, sample_targets


def _sha256_bounded(path: Path) -> str:
    size = path.stat().st_size
    if size > MAX_HASH_FILE_BYTES:
        raise ValueError(f"file exceeds {MAX_HASH_FILE_BYTES}-byte hash safety limit")
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        while True:
            block = handle.read(1024 * 1024)
            if not block:
                break
            digest.update(block)
    return digest.hexdigest()


def _frame_id_from_metadata(path: Path, metadata: Mapping[str, object]) -> str:
    supplied = metadata.get("frameId")
    if isinstance(supplied, str) and supplied:
        return supplied.removesuffix("_rgb")
    return path.name.removesuffix("_depth.json")


def _bbox(value: object) -> tuple[float, float, float, float] | None:
    if not isinstance(value, (list, tuple)) or len(value) != 4:
        return None
    parts = tuple(_finite_number(item) for item in value)
    if any(item is None for item in parts):
        return None
    return parts  # type: ignore[return-value]


def _validate_frames(
    saved_dir: Path,
    *,
    max_frames: int,
) -> tuple[
    dict[str, object],
    list[dict[str, object]],
    dict[tuple[str, str], dict[str, object]],
]:
    checks: list[dict[str, object]] = []
    frames_root = saved_dir / "frames"
    metadata_paths = [] if not frames_root.is_dir() else list(frames_root.glob("*/*_depth.json"))
    metadata_paths.sort(key=lambda path: (path.stat().st_mtime_ns, str(path)), reverse=True)
    truncated = len(metadata_paths) > max_frames
    selected = metadata_paths[:max_frames]
    if not selected:
        checks.append(_check("frames.metadata_present", "warn", "No frame metadata files were found."))
        return {
            "frames_root": str(frames_root.resolve()),
            "metadata_found": 0,
            "frames_examined": 0,
            "truncated_by_frame_limit": False,
            "pillow_available": False,
            "files": [],
            "visibility": [],
        }, checks, {}
    checks.append(_check("frames.metadata_present", "pass", "Frame metadata files were found.", found=len(metadata_paths), examined=len(selected)))
    if truncated:
        checks.append(_check("frames.frame_limit", "warn", "Frame validation was truncated at the configured limit.", max_frames=max_frames))

    try:
        from PIL import Image, ImageChops, ImageStat
        pillow_available = True
    except (ImportError, ModuleNotFoundError):
        Image = ImageChops = ImageStat = None  # type: ignore[assignment]
        pillow_available = False

    missing_files = 0
    metadata_errors = 0
    decode_errors = 0
    dimension_mismatches = 0
    bad_hashes = 0
    nondegenerate_rgb = 0
    nondegenerate_depth = 0
    depth_range_errors = 0
    depth_clipped_metadata = 0
    bbox_errors = 0
    bbox_examined = 0
    target_truth_missing = 0
    file_rows: list[dict[str, object]] = []
    metadata_index: dict[tuple[str, str], dict[str, object]] = {}
    visibility: dict[tuple[str, str], dict[str, object]] = {}
    decoded_rgb: dict[str, list[tuple[str, object]]] = defaultdict(list)

    for metadata_path in selected:
        base = metadata_path.name.removesuffix("_depth.json")
        rgb_path = metadata_path.with_name(base + "_rgb.png")
        depth_path = metadata_path.with_name(base + "_depth.png")
        row: dict[str, object] = {
            "metadata_path": str(metadata_path.resolve()),
            "rgb_path": str(rgb_path.resolve()),
            "depth_path": str(depth_path.resolve()),
            "rgb_exists": rgb_path.is_file(),
            "depth_exists": depth_path.is_file(),
        }
        if not rgb_path.is_file() or not depth_path.is_file():
            missing_files += int(not rgb_path.is_file()) + int(not depth_path.is_file())
        try:
            metadata = _load_json_object(metadata_path, MAX_METADATA_BYTES)
        except (OSError, UnicodeDecodeError, json.JSONDecodeError, ValueError) as exc:
            metadata_errors += 1
            row["metadata_error"] = str(exc)
            file_rows.append(row)
            continue
        node_id = metadata.get("nodeId")
        if not isinstance(node_id, str) or not node_id:
            node_id = metadata_path.parent.name
        frame_id = _frame_id_from_metadata(metadata_path, metadata)
        row["node_id"] = node_id
        row["frame_id"] = frame_id
        width = _finite_number(metadata.get("width"))
        height = _finite_number(metadata.get("height"))
        if width is None or height is None or width <= 0 or height <= 0:
            dimension_mismatches += 1
        metadata_index[(node_id, frame_id)] = metadata
        metadata_index[(node_id, frame_id + "_rgb")] = metadata

        minimum_depth = _finite_number(metadata.get("minimumObservedMeters"))
        maximum_depth = _finite_number(metadata.get("maximumObservedMeters"))
        normalization_max = _finite_number(metadata.get("normalizationMaxMeters"))
        valid_depth_range = (
            minimum_depth is not None
            and maximum_depth is not None
            and normalization_max is not None
            and minimum_depth >= 0.0
            and maximum_depth >= minimum_depth
            and normalization_max > 0.0
        )
        if not valid_depth_range:
            depth_range_errors += 1
        elif maximum_depth > normalization_max:
            depth_clipped_metadata += 1
        row["depth_metadata_valid"] = valid_depth_range
        row["depth_exceeds_png_normalization"] = bool(
            valid_depth_range and maximum_depth > normalization_max  # type: ignore[operator]
        )

        for label, path in (("rgb", rgb_path), ("depth", depth_path)):
            if not path.is_file():
                continue
            try:
                row[f"{label}_sha256"] = _sha256_bounded(path)
                row[f"{label}_bytes"] = path.stat().st_size
            except (OSError, ValueError) as exc:
                bad_hashes += 1
                row[f"{label}_hash_error"] = str(exc)

        if pillow_available and rgb_path.is_file() and depth_path.is_file():
            try:
                with Image.open(rgb_path) as source:  # type: ignore[union-attr]
                    source.verify()
                with Image.open(rgb_path) as source:  # type: ignore[union-attr]
                    rgb = source.convert("RGB").copy()
                with Image.open(depth_path) as source:  # type: ignore[union-attr]
                    source.verify()
                with Image.open(depth_path) as source:  # type: ignore[union-attr]
                    depth = source.convert("L").copy()
                expected_size = (int(width), int(height)) if width and height else None
                if expected_size is not None and (rgb.size != expected_size or depth.size != expected_size):
                    dimension_mismatches += 1
                rgb_gray = rgb.convert("L")
                rgb_stat = ImageStat.Stat(rgb_gray)  # type: ignore[union-attr]
                depth_stat = ImageStat.Stat(depth)  # type: ignore[union-attr]
                rgb_stddev = float(rgb_stat.stddev[0])
                depth_stddev = float(depth_stat.stddev[0])
                row["rgb_luminance_mean"] = float(rgb_stat.mean[0])
                row["rgb_luminance_stddev"] = rgb_stddev
                row["depth_gray_stddev"] = depth_stddev
                nondegenerate_rgb += int(rgb_stddev > 0.5)
                nondegenerate_depth += int(depth_stddev > 0.1)
                decoded_rgb[node_id].append((frame_id, rgb_gray))
            except (OSError, ValueError, SyntaxError) as exc:
                decode_errors += 1
                row["decode_error"] = str(exc)

        targets = metadata.get("targets")
        if isinstance(targets, list):
            for target in targets:
                if not isinstance(target, dict):
                    bbox_errors += 1
                    continue
                actor = target.get("actorName", target.get("targetActor"))
                actor_name = actor if isinstance(actor, str) and actor else "<unknown-target>"
                truth = _record_truth(target)
                if truth is None:
                    target_truth_missing += 1
                intersects = _truth_value(target.get("intersectsFrame"))
                box = _bbox(target.get("bboxXyxyPixels"))
                item = visibility.setdefault(
                    (node_id, actor_name),
                    {
                        "node_id": node_id,
                        "actor_name": actor_name,
                        "hostile_scenario_truth": truth,
                        "metadata_appearances": 0,
                        "intersects_frame_count": 0,
                        "valid_in_frame_bbox_count": 0,
                    },
                )
                item["metadata_appearances"] += 1  # type: ignore[operator]
                item["intersects_frame_count"] += int(intersects is True)  # type: ignore[operator]
                if box is not None:
                    bbox_examined += 1
                    x1, y1, x2, y2 = box
                    ordered = x1 <= x2 and y1 <= y2
                    in_bounds = (
                        width is not None
                        and height is not None
                        and 0.0 <= x1 < x2 <= width
                        and 0.0 <= y1 < y2 <= height
                    )
                    if not ordered or (intersects is True and not in_bounds):
                        bbox_errors += 1
                    if intersects is True and in_bounds:
                        item["valid_in_frame_bbox_count"] += 1  # type: ignore[operator]
                elif intersects is True:
                    bbox_errors += 1
        file_rows.append(row)

    checks.append(
        _check(
            "frames.paired_files",
            "pass" if missing_files == 0 else "fail",
            "Every selected metadata file has paired RGB and depth PNG files."
            if missing_files == 0
            else "One or more selected frame files are missing their RGB/depth pair.",
            missing_files=missing_files,
            metadata_files=len(selected),
        )
    )
    checks.append(
        _check(
            "frames.metadata_and_depth_ranges",
            "pass" if metadata_errors == 0 and depth_range_errors == 0 else "fail",
            "Frame metadata and depth ranges are finite and ordered."
            if metadata_errors == 0 and depth_range_errors == 0
            else "One or more metadata files or depth ranges are invalid.",
            metadata_errors=metadata_errors,
            invalid_depth_ranges=depth_range_errors,
            depth_ranges_exceeding_png_normalization=depth_clipped_metadata,
        )
    )
    if depth_clipped_metadata:
        checks.append(
            _check(
                "frames.depth_normalization_clipping",
                "warn",
                "Some observed depth maxima exceed the normalized PNG range and are clipped in the preview encoding.",
                affected_frames=depth_clipped_metadata,
            )
        )
    checks.append(
        _check(
            "frames.file_hashes",
            "pass" if bad_hashes == 0 else "fail",
            "Selected RGB/depth files were hashed successfully."
            if bad_hashes == 0
            else "One or more selected files could not be safely hashed.",
            hash_errors=bad_hashes,
        )
    )
    frame_differences: list[float] = []
    if not pillow_available:
        checks.append(_check("frames.image_decode", "warn", "Pillow is unavailable; image decodability, dimensions, and pixels were not inspected."))
    else:
        checks.append(
            _check(
                "frames.image_decode",
                "pass" if decode_errors == 0 and dimension_mismatches == 0 else "fail",
                "Selected images decode and match metadata dimensions."
                if decode_errors == 0 and dimension_mismatches == 0
                else "One or more images failed decoding or have inconsistent dimensions.",
                decode_errors=decode_errors,
                dimension_mismatches=dimension_mismatches,
            )
        )
        for frames in decoded_rgb.values():
            frames.sort(key=lambda pair: pair[0])
            for (_, previous), (_, current) in zip(frames, frames[1:]):
                if previous.size != current.size:  # type: ignore[attr-defined]
                    continue
                difference = ImageChops.difference(previous, current)  # type: ignore[union-attr]
                frame_differences.append(float(ImageStat.Stat(difference).mean[0]))  # type: ignore[union-attr]
        degenerate_rgb = max(0, len(file_rows) - metadata_errors - decode_errors - nondegenerate_rgb)
        checks.append(
            _check(
                "frames.rgb_nondegenerate",
                "pass" if nondegenerate_rgb > 0 and degenerate_rgb == 0 else ("warn" if nondegenerate_rgb > 0 else "fail"),
                "RGB luminance is non-degenerate in every decoded frame."
                if nondegenerate_rgb > 0 and degenerate_rgb == 0
                else "Some or all decoded RGB frames have near-constant luminance.",
                nondegenerate_frames=nondegenerate_rgb,
                near_constant_frames=degenerate_rgb,
            )
        )
        checks.append(
            _check(
                "frames.depth_nondegenerate",
                "pass" if nondegenerate_depth > 0 else "fail",
                "At least one depth preview has non-degenerate pixel values."
                if nondegenerate_depth > 0
                else "All decoded depth previews are near-constant.",
                nondegenerate_frames=nondegenerate_depth,
            )
        )
        if frame_differences:
            changing = sum(value > 0.1 for value in frame_differences)
            checks.append(
                _check(
                    "frames.temporal_difference",
                    "pass" if changing > 0 else "fail",
                    "At least one adjacent RGB pair changes over time."
                    if changing > 0
                    else "No adjacent decoded RGB pair changes appreciably.",
                    adjacent_pairs=len(frame_differences),
                    changing_pairs=changing,
                    mean_absolute_luminance_difference=sum(frame_differences) / len(frame_differences),
                )
            )
        else:
            checks.append(_check("frames.temporal_difference", "warn", "No adjacent same-node RGB pair was available."))

    if bbox_examined == 0:
        checks.append(_check("frames.projected_target_boxes", "warn", "No projected target bounding boxes were present in frame metadata."))
    else:
        checks.append(
            _check(
                "frames.projected_target_boxes",
                "pass" if bbox_errors == 0 else "fail",
                "All intersecting projected target boxes are ordered and within frame bounds."
                if bbox_errors == 0
                else "One or more projected target boxes are invalid or out of bounds.",
                boxes_examined=bbox_examined,
                errors=bbox_errors,
                target_truth_missing=target_truth_missing,
            )
        )

    summary = {
        "frames_root": str(frames_root.resolve()),
        "metadata_found": len(metadata_paths),
        "frames_examined": len(selected),
        "truncated_by_frame_limit": truncated,
        "pillow_available": pillow_available,
        "paired_file_missing_count": missing_files,
        "metadata_error_count": metadata_errors,
        "decode_error_count": decode_errors,
        "dimension_mismatch_count": dimension_mismatches,
        "rgb_luminance_nondegenerate_count": nondegenerate_rgb,
        "depth_preview_nondegenerate_count": nondegenerate_depth,
        "adjacent_rgb_difference": _distribution(frame_differences),
        "visibility": sorted(visibility.values(), key=lambda row: (str(row["node_id"]), str(row["actor_name"]))),
        "files": file_rows,
    }
    return summary, checks, metadata_index


def _confirming_node_count(alert: Mapping[str, object]) -> int | None:
    value = alert.get("confirmingNodes")
    if isinstance(value, list):
        node_ids: set[str] = set()
        for item in value:
            if isinstance(item, Mapping):
                node_id = item.get("nodeId", item.get("node_id"))
                if isinstance(node_id, str) and node_id.strip():
                    node_ids.add(node_id.strip())
            elif isinstance(item, str) and item.strip():
                node_ids.add(item.strip())
        if node_ids:
            return len(node_ids)
    numeric = _finite_number(value)
    if numeric is None:
        numeric = _finite_number(alert.get("confirmingNodeCount"))
    if numeric is None:
        node_ids = alert.get("confirmingNodeIds")
        if isinstance(node_ids, list):
            return len({str(item) for item in node_ids})
    if numeric is None or numeric < 0 or not numeric.is_integer():
        return None
    return int(numeric)


def _active_alert(record: Mapping[str, object]) -> bool:
    for key in ("eventType", "alertEvent", "state"):
        value = record.get(key)
        if isinstance(value, str) and value.lower() in {"clear", "cleared", "resolved", "inactive"}:
            return False
    if record.get("alertActive") is False:
        return False
    return True


def _alert_evidence_estimate(
    alerts: Sequence[dict[str, object]],
    sample_targets: Mapping[tuple[str, str], Mapping[str, object]],
    *,
    confirming_nodes_min: int,
    cooldown_seconds: float,
) -> dict[str, object]:
    by_target: dict[str, list[tuple[float, str]]] = defaultdict(list)
    evidence_times: list[float] = []
    for entry in sample_targets.values():
        if entry.get("truth") is not True:
            continue
        detected_nodes = entry.get("detected_nodes")
        if not isinstance(detected_nodes, set) or len(detected_nodes) < confirming_nodes_min:
            continue
        when = _finite_number(entry.get("simulation_seconds"))
        if when is None:
            continue
        target = str(entry.get("target", "<unknown-target>"))
        by_target[target].append((when, str(entry.get("sample"))))
        evidence_times.append(when)
    if not evidence_times:
        return {
            "feasible": False,
            "reason": "No timed hostile multi-node RF truth samples were available.",
            "qualifying_rf_samples": 0,
            "evidence_episodes": 0,
            "missed_alert_episodes": None,
            "unmatched_alerts": None,
        }
    unique_times = sorted(set(evidence_times))
    gaps = [right - left for left, right in zip(unique_times, unique_times[1:]) if right > left]
    cadence = statistics.median(gaps) if gaps else 0.5
    continuity_gap = max(0.05, cadence * 2.5)
    episodes: list[dict[str, object]] = []
    for target, values in by_target.items():
        values.sort()
        start = end = values[0][0]
        samples = 1
        for when, _ in values[1:]:
            if when - end <= continuity_gap:
                end = when
                samples += 1
            else:
                episodes.append({"target": target, "start": start, "end": end, "samples": samples})
                start = end = when
                samples = 1
        episodes.append({"target": target, "start": start, "end": end, "samples": samples})

    all_sample_times = [
        value
        for entry in sample_targets.values()
        if (value := _finite_number(entry.get("simulation_seconds"))) is not None
    ]
    observed_start = min(all_sample_times) if all_sample_times else min(evidence_times)
    observed_end = max(all_sample_times) if all_sample_times else max(evidence_times)
    alert_rows: list[tuple[int, str, float]] = []
    alerts_outside_rf_window = 0
    for index, alert in enumerate(alerts):
        if not _active_alert(alert):
            continue
        when, basis = _record_time(alert)
        if when is None or basis != "simulation":
            continue
        # A bounded/truncated RF read cannot adjudicate alerts beyond the RF
        # interval it actually contains.  Exclude those instead of manufacturing
        # unmatched-alert failures from unequal input windows.
        if when < observed_start - cooldown_seconds or when > observed_end + cooldown_seconds:
            alerts_outside_rf_window += 1
            continue
        alert_rows.append((index, _target_name(alert), when))

    matched_alert_indices: set[int] = set()
    missed = 0
    tolerance = max(cooldown_seconds, continuity_gap)
    for episode in episodes:
        matches = [
            index
            for index, target, when in alert_rows
            if target == episode["target"]
            and float(episode["start"]) - tolerance <= when <= float(episode["end"]) + tolerance
        ]
        if matches:
            matched_alert_indices.update(matches)
        else:
            missed += 1
    unmatched = sum(index not in matched_alert_indices for index, _, _ in alert_rows)
    return {
        "feasible": True,
        "basis": "simulation scenario truth and RF boolean multi-node gates",
        "qualifying_rf_samples": sum(len(values) for values in by_target.values()),
        "evidence_episodes": len(episodes),
        "missed_alert_episodes": missed,
        "timed_active_alerts": len(alert_rows),
        "alerts_outside_observed_rf_window": alerts_outside_rf_window,
        "observed_rf_window_simulation_seconds": [observed_start, observed_end],
        "unmatched_alerts": unmatched,
        "estimated_sample_cadence_seconds": cadence,
        "episode_continuity_gap_seconds": continuity_gap,
        "match_tolerance_seconds": tolerance,
        "episodes": episodes[:1_000],
        "not_physical_performance_metrics": True,
    }


def _validate_alerts(
    alerts: Sequence[dict[str, object]],
    sample_targets: Mapping[tuple[str, str], Mapping[str, object]],
    *,
    confirming_nodes_min: int,
    cooldown_seconds: float,
) -> tuple[dict[str, object], list[dict[str, object]]]:
    checks: list[dict[str, object]] = []
    active = [record for record in alerts if _active_alert(record)]
    non_hostile = sum(_record_truth(record) is False for record in active)
    unknown_truth = sum(_record_truth(record) is None for record in active)
    if not alerts:
        checks.append(_check("alerts.records_present", "warn", "No alert records were available."))
    else:
        checks.append(_check("alerts.records_present", "pass", "Alert records were available.", records=len(alerts), active_records=len(active)))
    if active:
        checks.append(
            _check(
                "alerts.hostile_only",
                "fail" if non_hostile else ("warn" if unknown_truth else "pass"),
                "Every active alert has hostile scenario truth."
                if not non_hostile and not unknown_truth
                else "Some active alerts are non-hostile or lack hostile scenario truth.",
                non_hostile_alerts=non_hostile,
                unknown_truth_alerts=unknown_truth,
            )
        )
    node_counts = [_confirming_node_count(record) for record in active]
    node_counts_known = [count for count in node_counts if count is not None]
    below_minimum = 0
    for record, count in zip(active, node_counts):
        if count is None:
            continue
        record_minimum = _finite_number(record.get("minimumConfirmingNodes"))
        required = confirming_nodes_min
        if record_minimum is not None and record_minimum >= 1 and record_minimum.is_integer():
            required = max(required, int(record_minimum))
        below_minimum += int(count < required)
    if not active:
        checks.append(_check("alerts.confirming_nodes", "warn", "No active alert could be checked for node confirmation."))
    elif not node_counts_known:
        checks.append(_check("alerts.confirming_nodes", "warn", "confirmingNodes was absent from active alerts."))
    else:
        checks.append(
            _check(
                "alerts.confirming_nodes",
                "pass" if below_minimum == 0 else "fail",
                "Every checkable active alert meets the configured node-confirmation minimum."
                if below_minimum == 0
                else "One or more active alerts are below the node-confirmation minimum.",
                compared=len(node_counts_known),
                below_minimum=below_minimum,
                configured_minimum=confirming_nodes_min,
            )
        )

    distance_records = [
        record
        for record in active
        if any(
            key in record
            for key in (
                "distanceValid",
                "distanceSemantics",
                "nearestConfirmingNodeId",
                "nearestConfirmingNodeDistanceMeters",
                "confirmingNodes",
            )
        )
    ]
    distance_checkable = 0
    distance_errors = 0
    per_node_distances_checked = 0
    for record in distance_records:
        if record.get("distanceValid") is False:
            continue
        nearest_node = record.get("nearestConfirmingNodeId")
        nearest_distance = _finite_number(record.get("nearestConfirmingNodeDistanceMeters"))
        semantics = record.get("distanceSemantics")
        confirming_nodes = record.get("confirmingNodes")
        if not isinstance(nearest_node, str) or not nearest_node.strip() or nearest_distance is None:
            distance_errors += 1
            continue
        distance_checkable += 1
        if nearest_distance < 0.0 or semantics != "sensor_to_target_3d_slant_range":
            distance_errors += 1
        if not isinstance(confirming_nodes, list):
            distance_errors += 1
            continue
        parsed_distances: list[tuple[str, float]] = []
        for item in confirming_nodes:
            if not isinstance(item, Mapping):
                distance_errors += 1
                continue
            node_id = item.get("nodeId", item.get("node_id"))
            slant_distance = _finite_number(
                item.get("slantDistanceMeters", item.get("slant_distance_meters"))
            )
            if not isinstance(node_id, str) or not node_id.strip() or slant_distance is None or slant_distance < 0.0:
                distance_errors += 1
                continue
            parsed_distances.append((node_id.strip(), slant_distance))
            per_node_distances_checked += 1
        if parsed_distances:
            expected_node, expected_distance = min(parsed_distances, key=lambda item: (item[1], item[0]))
            if nearest_node.strip() != expected_node or abs(nearest_distance - expected_distance) > 1e-6:
                distance_errors += 1
        else:
            distance_errors += 1
    if not distance_records:
        checks.append(
            _check(
                "alerts.distance_fields",
                "warn",
                "Alert range fields were absent; older alert schemas remain supported.",
            )
        )
    elif distance_checkable == 0:
        checks.append(
            _check(
                "alerts.distance_fields",
                "warn",
                "No active alert contained a checkable valid range.",
                records_with_distance_schema=len(distance_records),
            )
        )
    else:
        checks.append(
            _check(
                "alerts.distance_fields",
                "pass" if distance_errors == 0 else "fail",
                "Alert nearest-node ranges are finite, use 3D slant-range semantics, and match the per-node minimum."
                if distance_errors == 0
                else "One or more alert nearest-node ranges are malformed or inconsistent with their per-node ranges.",
                records_checked=distance_checkable,
                per_node_distances_checked=per_node_distances_checked,
                errors=distance_errors,
            )
        )

    cooldown_violations = 0
    timed_pairs = 0
    per_target_times: dict[tuple[str, str], list[float]] = defaultdict(list)
    for record in active:
        when, basis = _record_time(record)
        if when is not None:
            per_target_times[(_target_name(record), basis)].append(when)
    for times in per_target_times.values():
        times.sort()
        for left, right in zip(times, times[1:]):
            timed_pairs += 1
            if right - left + 1e-6 < cooldown_seconds:
                cooldown_violations += 1
    if timed_pairs == 0:
        checks.append(_check("alerts.cooldown", "warn", "There were no repeated timed alerts to test cooldown behavior."))
    else:
        checks.append(
            _check(
                "alerts.cooldown",
                "pass" if cooldown_violations == 0 else "fail",
                "Repeated alerts respect the configured per-target cooldown."
                if cooldown_violations == 0
                else "One or more per-target alerts violate the configured cooldown.",
                compared_intervals=timed_pairs,
                violations=cooldown_violations,
                cooldown_seconds=cooldown_seconds,
            )
        )

    non_detection_only = sum(record.get("detectionOnly") is False for record in active)
    disallowed_actions = 0
    allowed_actions = {"", "none", "log", "logged", "visual_alert", "audio_alert", "notify"}
    for record in active:
        actions = record.get("actionsTaken")
        values = actions if isinstance(actions, list) else [actions]
        for value in values:
            if value is not None and str(value).strip().lower() not in allowed_actions:
                disallowed_actions += 1
    if active:
        checks.append(
            _check(
                "alerts.detection_only",
                "pass" if non_detection_only == 0 and disallowed_actions == 0 else "fail",
                "Alerts are detection-only and record no engagement action."
                if non_detection_only == 0 and disallowed_actions == 0
                else "One or more alerts are not detection-only or record a disallowed action.",
                non_detection_only_records=non_detection_only,
                disallowed_action_values=disallowed_actions,
            )
        )

    evidence = _alert_evidence_estimate(
        active,
        sample_targets,
        confirming_nodes_min=confirming_nodes_min,
        cooldown_seconds=cooldown_seconds,
    )
    if not evidence["feasible"]:
        checks.append(_check("alerts.scenario_truth_estimate", "warn", str(evidence["reason"])))
    else:
        missed = int(evidence["missed_alert_episodes"])
        unmatched = int(evidence["unmatched_alerts"])
        checks.append(
            _check(
                "alerts.scenario_truth_estimate",
                "pass" if missed == 0 and unmatched == 0 else "fail",
                "Every RF hostile multi-node episode has a matching alert and every timed alert has matching evidence."
                if missed == 0 and unmatched == 0
                else "Scenario-truth evidence indicates missed episodes or unmatched alerts.",
                missed_alert_episodes=missed,
                unmatched_alerts=unmatched,
                diagnostic_scope="simulation scenario truth; not real-world false-alarm validation",
            )
        )
    return {
        "record_count": len(alerts),
        "active_alert_count": len(active),
        "hostile_active_alert_count": sum(_record_truth(record) is True for record in active),
        "non_hostile_active_alert_count": non_hostile,
        "unknown_truth_active_alert_count": unknown_truth,
        "distance_schema_record_count": len(distance_records),
        "distance_checkable_record_count": distance_checkable,
        "distance_error_count": distance_errors,
        "scenario_truth_evidence_estimate": evidence,
    }, checks


def _candidate_rows(report: Mapping[str, object]) -> list[dict[str, object]]:
    candidates = report.get("candidates")
    if isinstance(candidates, list):
        return [item for item in candidates if isinstance(item, dict)]
    event = report.get("event_camera")
    if isinstance(event, dict):
        samples = event.get("observation_samples", event.get("candidates"))
        if isinstance(samples, list):
            return [item for item in samples if isinstance(item, dict)]
    return []


def _box_iou(left: tuple[float, float, float, float], right: tuple[float, float, float, float]) -> float:
    ix1 = max(left[0], right[0])
    iy1 = max(left[1], right[1])
    ix2 = min(left[2], right[2])
    iy2 = min(left[3], right[3])
    intersection = max(0.0, ix2 - ix1) * max(0.0, iy2 - iy1)
    left_area = max(0.0, left[2] - left[0]) * max(0.0, left[3] - left[1])
    right_area = max(0.0, right[2] - right[0]) * max(0.0, right[3] - right[1])
    union = left_area + right_area - intersection
    return intersection / union if union > 0.0 else 0.0


def _event_proxy_diagnostic(
    event_report_path: Path | None,
    metadata_index: Mapping[tuple[str, str], Mapping[str, object]],
) -> tuple[dict[str, object], list[dict[str, object]]]:
    checks: list[dict[str, object]] = []
    if event_report_path is None:
        checks.append(_check("event.report_included", "warn", "No event experiment report was supplied."))
        return {
            "included": False,
            "proxy_non_equivalence": True,
            "candidate_activations_are_true_positives": False,
        }, checks
    try:
        report = _load_json_object(event_report_path, MAX_EVENT_REPORT_BYTES)
    except (OSError, UnicodeDecodeError, json.JSONDecodeError, ValueError) as exc:
        checks.append(_check("event.report_included", "fail", f"Event report could not be read: {exc}"))
        return {
            "included": False,
            "path": str(event_report_path),
            "proxy_non_equivalence": True,
            "candidate_activations_are_true_positives": False,
        }, checks

    candidates = _candidate_rows(report)
    event_section = report.get("event_camera")
    source = report.get("source_encoding")
    equivalent = report.get("preprocessing_equivalent_to_training")
    declared_count = report.get("candidate_count")
    if isinstance(event_section, dict):
        source = event_section.get("source_encoding", source)
        equivalent = event_section.get("preprocessing_equivalent_to_training", equivalent)
        declared_count = event_section.get("event_observation_count", declared_count)
    checks.append(_check("event.report_included", "pass", "The event experiment report was included.", path=str(event_report_path.resolve())))
    checks.append(
        _check(
            "event.proxy_equivalence",
            "warn",
            "Event candidates use an RGB-derived proxy that is not equivalent to the training event stack; candidates are activations, not validated true positives.",
            source_encoding=source,
            preprocessing_equivalent_to_training=equivalent,
        )
    )

    best_ious: list[float] = []
    center_inside = 0
    candidates_with_metadata = 0
    gt_boxes_compared = 0
    for candidate in candidates:
        measurements = candidate.get("measurements")
        if not isinstance(measurements, dict):
            measurements = candidate
        node = candidate.get("node_id", candidate.get("nodeId"))
        frame = measurements.get("frame_id", measurements.get("frameId"))
        if not isinstance(node, str) or not isinstance(frame, str):
            continue
        normalized = _bbox(measurements.get("bbox_xyxy_normalized"))
        pixels = _bbox(measurements.get("bboxXyxyPixels"))
        metadata = metadata_index.get((node, frame)) or metadata_index.get((node, frame.removesuffix("_rgb")))
        if metadata is None:
            continue
        width = _finite_number(metadata.get("width"))
        height = _finite_number(metadata.get("height"))
        if pixels is None and normalized is not None and width and height:
            pixels = (
                normalized[0] * width,
                normalized[1] * height,
                normalized[2] * width,
                normalized[3] * height,
            )
        if pixels is None:
            continue
        candidates_with_metadata += 1
        ground_truth_boxes: list[tuple[float, float, float, float]] = []
        targets = metadata.get("targets")
        if isinstance(targets, list):
            for target in targets:
                if not isinstance(target, dict) or _truth_value(target.get("intersectsFrame")) is not True:
                    continue
                truth_box = _bbox(target.get("bboxXyxyPixels"))
                if truth_box is not None:
                    ground_truth_boxes.append(truth_box)
        if not ground_truth_boxes:
            continue
        gt_boxes_compared += len(ground_truth_boxes)
        ious = [_box_iou(pixels, truth_box) for truth_box in ground_truth_boxes]
        best_ious.append(max(ious))
        center_x = (pixels[0] + pixels[2]) / 2.0
        center_y = (pixels[1] + pixels[3]) / 2.0
        center_inside += int(
            any(box[0] <= center_x <= box[2] and box[1] <= center_y <= box[3] for box in ground_truth_boxes)
        )

    if best_ious:
        checks.append(
            _check(
                "event.proxy_gt_overlap_diagnostic",
                "warn",
                "Proxy candidate/scene-truth overlap was calculated descriptively; it is not precision, recall, or true-positive validation.",
                candidates_compared=len(best_ious),
                mean_best_iou=math.fsum(best_ious) / len(best_ious),
                candidate_centers_inside_projected_truth=center_inside,
            )
        )
    else:
        checks.append(
            _check(
                "event.proxy_gt_overlap_diagnostic",
                "warn",
                "No event candidate could be aligned with projected simulation target metadata for a descriptive overlap diagnostic.",
                candidate_rows=len(candidates),
                candidates_with_matching_metadata=candidates_with_metadata,
            )
        )
    declared_numeric = _finite_number(declared_count)
    return {
        "included": True,
        "path": str(event_report_path.resolve()),
        "source_encoding": source,
        "preprocessing_equivalent_to_training": equivalent is True,
        "proxy_non_equivalence": True,
        "candidate_activation_count_declared": int(declared_numeric) if declared_numeric is not None else None,
        "candidate_rows_available": len(candidates),
        "candidate_activations_are_true_positives": False,
        "diagnostic_only": True,
        "projected_simulation_truth_overlap": {
            "candidates_with_matching_metadata": candidates_with_metadata,
            "candidates_compared": len(best_ious),
            "projected_target_boxes_compared": gt_boxes_compared,
            "mean_best_iou": math.fsum(best_ious) / len(best_ious) if best_ious else None,
            "maximum_best_iou": max(best_ious) if best_ious else None,
            "candidate_centers_inside_projected_truth": center_inside,
            "not_precision_or_recall": True,
            "not_true_positive_validation": True,
        },
    }, checks


def _overall_status(checks: Iterable[Mapping[str, object]]) -> str:
    status = "pass"
    for check in checks:
        candidate = check.get("status")
        if isinstance(candidate, str) and candidate in {"pass", "warn", "fail"}:
            if _status_rank(candidate) > _status_rank(status):
                status = candidate
    return status


def run_validation_campaign(
    *,
    saved_dir: str | Path = DEFAULT_SAVED_DIR,
    rf_jsonl: str | Path | None = None,
    alerts_jsonl: str | Path | None = None,
    scenario_config: str | Path | None = DEFAULT_CONFIG_PATH,
    event_report: str | Path | None = None,
    max_rf_records: int = DEFAULT_MAX_RF_RECORDS,
    max_alert_records: int = DEFAULT_MAX_ALERT_RECORDS,
    max_frames: int = DEFAULT_MAX_FRAMES,
    confirming_nodes_min: int | None = None,
    alert_cooldown_seconds: float | None = None,
) -> dict[str, object]:
    """Validate one bounded campaign using only recorded simulation artifacts."""

    rf_limit = _positive_bounded("max_rf_records", max_rf_records, MAX_RF_RECORDS_HARD_LIMIT)
    alert_limit = _positive_bounded("max_alert_records", max_alert_records, MAX_ALERT_RECORDS_HARD_LIMIT)
    frame_limit = _positive_bounded("max_frames", max_frames, MAX_FRAMES_HARD_LIMIT)
    saved = Path(saved_dir).expanduser().resolve()
    selected_rf = Path(rf_jsonl).expanduser().resolve() if rf_jsonl is not None else _newest_jsonl(saved, "rf_links_")
    selected_alerts = Path(alerts_jsonl).expanduser().resolve() if alerts_jsonl is not None else _newest_jsonl(saved, "alerts_")
    selected_config = Path(scenario_config).expanduser().resolve() if scenario_config is not None else None
    selected_event = Path(event_report).expanduser().resolve() if event_report is not None else None
    checks: list[dict[str, object]] = []
    config, config_checks = _scenario_config(selected_config)
    checks.extend(config_checks)
    configured_minimum = _finite_number(config.get("AlertMinimumConfirmingNodes"))
    if confirming_nodes_min is None:
        confirming_nodes_min = (
            int(configured_minimum)
            if configured_minimum is not None
            and configured_minimum >= 1
            and configured_minimum.is_integer()
            else 2
        )
    if isinstance(confirming_nodes_min, bool) or not isinstance(confirming_nodes_min, int) or confirming_nodes_min <= 0:
        raise ValueError("confirming_nodes_min must be a positive integer")
    configured_cooldown = _finite_number(config.get("AlertCooldownSeconds"))
    if alert_cooldown_seconds is None:
        alert_cooldown_seconds = configured_cooldown if configured_cooldown is not None else 10.0
    cooldown = _finite_number(alert_cooldown_seconds)
    if cooldown is None or cooldown < 0.0:
        raise ValueError("alert_cooldown_seconds must be finite and >= 0")

    if selected_rf is None:
        rf_records: list[dict[str, object]] = []
        rf_input = {"path": None, "records_read": 0}
        checks.append(_check("rf.input_selected", "fail", "No rf_links_*.jsonl file was found or specified."))
    else:
        checks.append(_check("rf.input_selected", "pass", "RF telemetry input was selected.", path=str(selected_rf)))
        rf_records, rf_input, rf_input_checks = _read_jsonl_bounded(selected_rf, max_records=rf_limit)
        checks.extend({**item, "id": "rf." + str(item["id"])} for item in rf_input_checks)
    rf_summary, rf_checks, sample_targets = _validate_rf(
        rf_records,
        config,
        confirming_nodes_min=confirming_nodes_min,
    )
    checks.extend(rf_checks)

    frames_summary, frame_checks, metadata_index = _validate_frames(saved, max_frames=frame_limit)
    checks.extend(frame_checks)

    if selected_alerts is None:
        alert_records: list[dict[str, object]] = []
        alert_input = {"path": None, "records_read": 0}
        checks.append(_check("alerts.input_selected", "warn", "No alerts_*.jsonl file was found or specified."))
    else:
        checks.append(_check("alerts.input_selected", "pass", "Alert telemetry input was selected.", path=str(selected_alerts)))
        alert_records, alert_input, alert_input_checks = _read_jsonl_bounded(selected_alerts, max_records=alert_limit)
        checks.extend({**item, "id": "alerts." + str(item["id"])} for item in alert_input_checks)
    alert_summary, alert_checks = _validate_alerts(
        alert_records,
        sample_targets,
        confirming_nodes_min=confirming_nodes_min,
        cooldown_seconds=cooldown,
    )
    checks.extend(alert_checks)

    event_summary, event_checks = _event_proxy_diagnostic(selected_event, metadata_index)
    checks.extend(event_checks)
    status = _overall_status(checks)
    counts = {candidate: sum(item["status"] == candidate for item in checks) for candidate in ("pass", "warn", "fail")}
    return {
        "schema_version": "1.0",
        "campaign_kind": "bounded_simulation_sensor_validation",
        "generated_at_utc": _utc_now(),
        "overall_status": status,
        "check_counts": counts,
        "scope": {
            "simulation_only": True,
            "detection_and_alerting_only": True,
            "engagement_logic_present": False,
            "physical_rf_calibration_claimed": False,
            "real_world_performance_claimed": False,
            "scenario_truth_is_real_world_ground_truth": False,
        },
        "limits": {
            "max_rf_records": rf_limit,
            "max_alert_records": alert_limit,
            "max_frames": frame_limit,
            "max_jsonl_line_bytes": MAX_JSONL_LINE_BYTES,
        },
        "inputs": {
            "saved_dir": str(saved),
            "scenario_config": None if selected_config is None else str(selected_config),
            "rf": rf_input,
            "alerts": alert_input,
            "event_report": None if selected_event is None else str(selected_event),
        },
        "rf": rf_summary,
        "rgb_depth": frames_summary,
        "alerts": alert_summary,
        "event_camera": event_summary,
        "checks": checks,
        "limitations": [
            "RF checks establish numerical and telemetry consistency only; no antenna, channel, clutter, interference, or receiver calibration against physical measurements is claimed.",
            "hostileScenarioTruth and projected target boxes are simulator scenario truth, not independently annotated real-world truth.",
            "RGB-derived proxy_event_stack_v1 is not equivalent to the neuromorphic event preprocessing used for training; candidate activations are not counted as true positives.",
            "Depth PNGs are normalized previews and may clip values above normalizationMaxMeters; raw metric depth is not reconstructed from clipped pixels.",
            "Alert missed/unmatched estimates are bounded scenario diagnostics based on RF boolean gates and recorded samples, not physical false-positive or false-negative rates.",
            "This validator and the simulation contain no engagement, interception, damage, weapon-control, or effector logic.",
        ],
    }


def write_report_atomic(report: Mapping[str, object], output_path: str | Path) -> Path:
    """Write a strict JSON report and atomically replace the destination."""

    destination = Path(output_path).expanduser().resolve()
    destination.parent.mkdir(parents=True, exist_ok=True)
    temporary: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            dir=destination.parent,
            prefix=f".{destination.name}.",
            suffix=".tmp",
            delete=False,
        ) as handle:
            temporary = Path(handle.name)
            json.dump(report, handle, indent=2, allow_nan=False)
            handle.write("\n")
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, destination)
    except Exception:
        if temporary is not None:
            try:
                temporary.unlink(missing_ok=True)
            except OSError:
                pass
        raise
    return destination


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Validate bounded Unreal RF, RGB/depth, event-proxy, and alert artifacts."
    )
    parser.add_argument("--saved-dir", default=str(DEFAULT_SAVED_DIR))
    parser.add_argument("--rf-jsonl", help="Specific rf_links JSONL; newest is used by default.")
    parser.add_argument("--alerts-jsonl", help="Specific alerts JSONL; newest is used by default.")
    parser.add_argument("--scenario-config", default=str(DEFAULT_CONFIG_PATH))
    parser.add_argument("--event-report", help="Optional experiment/candidate JSON report.")
    parser.add_argument("--output", required=True, help="Destination JSON report path.")
    parser.add_argument("--max-rf-records", type=int, default=DEFAULT_MAX_RF_RECORDS)
    parser.add_argument("--max-alert-records", type=int, default=DEFAULT_MAX_ALERT_RECORDS)
    parser.add_argument("--max-frames", type=int, default=DEFAULT_MAX_FRAMES)
    parser.add_argument("--confirming-nodes-min", type=int, help="Override config AlertMinimumConfirmingNodes.")
    parser.add_argument("--alert-cooldown-seconds", type=float, help="Override config AlertCooldownSeconds.")
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    report = run_validation_campaign(
        saved_dir=args.saved_dir,
        rf_jsonl=args.rf_jsonl,
        alerts_jsonl=args.alerts_jsonl,
        scenario_config=args.scenario_config,
        event_report=args.event_report,
        max_rf_records=args.max_rf_records,
        max_alert_records=args.max_alert_records,
        max_frames=args.max_frames,
        confirming_nodes_min=args.confirming_nodes_min,
        alert_cooldown_seconds=args.alert_cooldown_seconds,
    )
    destination = write_report_atomic(report, args.output)
    print(json.dumps({"output": str(destination), "overall_status": report["overall_status"], "check_counts": report["check_counts"]}))
    return 1 if report["overall_status"] == "fail" else 0


if __name__ == "__main__":
    raise SystemExit(main())
