#pragma once

// Generated from tree_geometry_instance_selector.v4.json. Eight adjacent
// literals keep the 736-entry table readable without runtime file access.
#define TRIAD_TREE_GEOMETRY_VARIATION_SELECTOR_TEXT \
    TEXT("CBCCAAAABAAAABABBCBBAAABCCAABACBBABCACCBBCCBCCBABCBABCCBBCACACBBCBBCBABABABBBACACACACBBCCCBB") \
    TEXT("ABBABBBBCAABCACBBCBBBCAABCCACABCAACABBBAACABBABCACACBCCBBCAACCACBBCBCBCCCAACBCCCACCCBCBBCACA") \
    TEXT("CBAAAABAAABCBBBBBBCCABACCBBABBACBACCBABCCAACCABACACBCCCCCBCBBCCBBBBBCACBAAAACAACBBBBBCACAABB") \
    TEXT("BCBCCCCCBACCACABAABBBCCAABAAACABABCACBCCABCCCBCBABABCCCAABCBACAABBACCBCABCBCCCBAABABCBCACACA") \
    TEXT("CCBAABAAABBAAACAACACBBCABCABBBACABAABCCAACBBAABBCBBACBBBBBAAACAACBBBCBAACBABACBCCBACBBABCCBC") \
    TEXT("BCCABCABBCCBCBCCCAACABCBBBCBACCABBBBCCACACBCCCABBCAABCCCCACBBBBBCBABBBCABBBBABAABBCBABABCACA") \
    TEXT("AAACBCBCCACBBBCBABBCBAABBCABBBAAABABACAACABBBCAAAACCACAACACCBBBBBCCCCAABBAACACACCBBBACCBBCAC") \
    TEXT("BCBAAABCABCABCAACBBBCACBBABBABBBBCBAACABCBCABBACCBBAACCCBCCCBABAACCABCCBCACCCACACCBBBACCBBBC")
